//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorio_PIII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentarios
    {
        public int ID { get; set; }
        public int ClienteID { get; set; }
        public int ProgramaID { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
