//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorio_PIII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizaciones
    {
        public int ID { get; set; }
        public string TipoMoneda { get; set; }
        public decimal Valor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
