//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorio_PIII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticias
    {
        public int ID { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public string Imagen { get; set; }
    }
}
