//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorio_PIII.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class obligatorioP3Entities1 : DbContext
    {
        public obligatorioP3Entities1()
            : base("name=obligatorioP3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
        public virtual DbSet<conductores> conductores { get; set; }
        public virtual DbSet<cotizaciones> cotizaciones { get; set; }
        public virtual DbSet<noticias> noticias { get; set; }
        public virtual DbSet<patrocinadores> patrocinadores { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<programas> programas { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<clima> clima { get; set; }
    }
}
