//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorio_PIII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDeAnuncios
    {
        public int ID { get; set; }
        public int PatrocinadorID { get; set; }
        public string Frecuencia { get; set; }
        public int Duracion { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public string TipoDeAnuncio { get; set; }
        public string Segmentacion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Nombre { get; set; }
    
        public virtual patrocinadores patrocinadores { get; set; }
    }
}
